show_between_topics:
  type: integer
  default: 20

show_between_posts:
  type: integer
  default: 10

exclude_categories:
  type: list
  list_type: category
  default: ""

ads:
  type: objects
  default: []
  schema:
    name: ad
    properties:
      link:
        type: string
      text:
        type: string
      include_groups:
        type: string
      exclude_groups:
        type: string
      utm_source:
        type: string
      utm_campaign:
        type: string
      utm_content:
        type: string
      custom_class:
        type: string

ads_impression_event_name:
  type: string
  default: "ads_impression"

plausible_integration_enabled:
  type: bool
  default: false
